### ISSUE TITLE
Add More Spin loading from spinkit

### ISSUE THREAD

**Issue by TonPC64** [TonPC64/vue-spinkit#4]
https://tobiasahlin.com/spinkit/

**Comment by Tarektouati** [comment]
i'll do it

**Comment by Tarektouati** [comment]
@TonPC64  you already added all SpinKit loaders  
`https://github.com/tobiasahlin/SpinKit/tree/master/css/spinners`
`https://github.com/TonPC64/vue-spinkit/blob/master/src/components/spinners.js#L1`

**Comment by TonPC64** [comment]
GG I'm so sorry
